### ISSUE TITLE
odpi-egeria-lab 3.9 fails on openshift: zookeeper: permission denied

### ISSUE THREAD

**Issue by planetf1** [odpi/egeria-charts#156]
When running the lab chart on a completely freshly installed (v 4.10) open shift cluster I get:|

```
➜  master git:(master) kubectl logs lab-strimzi-zookeeper-0        
Detected Zookeeper ID 1
mkdir: cannot create directory '/var/lib/zookeeper/data': Permission denied
```

This is from Strimzi 0.29, with the image 'quay.io/strimzi/kafka:0.29.0-kafka-3.0.0'

**Comment by planetf1** [comment]
This problem surfaced after creating a new cluster. It may be that a scc was previously edited.

The following addition to the kafka CR addresses this issue. This should be added to both the spec.kafka & spec.zookeeper sections:
```
    template:
      pod:
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
          fsGroup: 1001
```
