### ISSUE TITLE
Should the PTS charts install?

### ISSUE THREAD

**Issue by dwolfson** [odpi/egeria-charts#215]
I tried to install the PTS charts on my Mac and got the error:
`wolfson@Lazurus egeriaConnectors % helm install pts egeria/egeria-pts
Error: INSTALLATION FAILED: template: egeria-pts/templates/tut.yaml:80:32: executing "egeria-pts/templates/tut.yaml" at <.Values.image.egeria.registry>: nil pointer evaluating interface {}.egeria`

**Comment by dwolfson** [comment]
I get the same error on my Linux box..

**Comment by planetf1** [comment]
It should work, but does not.

The PTS chart is not included in our current release testing (and hasn't been run for a long time)

The error was introduced by some refactoring across the charts. To workaround this, create a file like ~/etc/pts.yaml
```
image:
  egeria:
    registry: quay.io
    name: egeria
  configure:
    registry: quay.io
    name: egeria-configure
```
and add `-f ~/etc/pts.yaml` to the invocation.

This at least gets things charted.

it does need fixing/
